# Generated by Django 5.2.1 on 2025-05-22 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Категорія документів',
                'verbose_name_plural': 'Категорії документів',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва місця зберігання')),
                ('room', models.CharField(max_length=50, verbose_name='Кімната')),
                ('shelf', models.CharField(max_length=50, verbose_name='Полиця')),
                ('box', models.CharField(blank=True, max_length=50, null=True, verbose_name='Коробка')),
            ],
            options={
                'verbose_name': 'Місце зберігання',
                'verbose_name_plural': 'Місця зберігання',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва документа')),
                ('document_type', models.CharField(choices=[('diploma', 'Диплом'), ('certificate', 'Сертифікат'), ('transcript', 'Академічна довідка'), ('order', 'Наказ'), ('protocol', 'Протокол'), ('report', 'Звіт'), ('other', 'Інше')], max_length=20, verbose_name='Тип документа')),
                ('document_number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('issue_date', models.DateField(verbose_name='Дата видачі')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення терміну дії')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Створено')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentcategory', verbose_name='Категорія')),
                ('storage_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.storagelocation', verbose_name='Місце зберігання')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Створення'), ('update', 'Оновлення'), ('view', 'Перегляд'), ('delete', 'Видалення')], max_length=10, verbose_name='Дія')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Деталі')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='documents.document', verbose_name='Документ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Історія документа',
                'verbose_name_plural': 'Історія документів',
                'ordering': ['-timestamp'],
            },
        ),
    ]
