# Generated by Django 5.2.1 on 2025-05-22 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва звіту')),
                ('report_type', models.CharField(choices=[('document_list', 'Список документів'), ('document_by_category', 'Документи за категоріями'), ('document_by_location', 'Документи за місцем зберігання'), ('document_by_date', 'Документи за датою'), ('activity_log', 'Журнал активності'), ('custom', 'Користувацький звіт')], max_length=20, verbose_name='Тип звіту')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Параметри')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Файл звіту')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Звіт',
                'verbose_name_plural': 'Звіти',
                'ordering': ['-created_at'],
            },
        ),
    ]
